services:
  contenedor1:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu-ping
    container_name: contenedor1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - red-integracion

  contenedor2:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu-ping
    container_name: contenedor2
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - red-integracion

networks:
  red-integracion:
    external: true
